# Generated by Django 2.2.4 on 2020-11-26 13:23

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emplo_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to=app.models.users.upload_dir)),
                ('result', models.FileField(blank=True, null=True, upload_to=app.models.users.upload_file)),
            ],
        ),
    ]
